###
base_url = "https://halve-z.netlify.app"
title = "Halve-Z Zola theme"
description = "Two-column retro theme for Zola"
default_language = "en"
author = "-k"
theme = "halve-z"

compile_sass = true
minify_html = true
generate_feed = true
build_search_index = true

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[search]
include_title = true
include_description = true
include_path = false
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
    { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]
render_emoji = false
external_links_target_blank = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
locale = "en_US"
logo = "icon-192x192.png"
manifest = "manifest.json"
read_time = true
toc = true
csp = true

[extra.home]
title = "Halve-Z"
subtitle = "Zola theme"
glitch = false
logo = { enabled = false, height = "100", width = "100" }
footer = true

[extra.images]
home = "https://failsafe.monster/c1tyh4ll.png"
post_list = "https://failsafe.monster/bk-prk.jpg"
default_post = "https://failsafe.monster/bk-prk.jpg"
categories = [
    { name = "media", image = "https://raw.githubusercontent.com/bearcott/8bit-art/master/cities/urban.gif" },
]

[extra.menu]
posts = true
links = [
    { name = "Code", url = "@/pages/projects.md" },
]

[extra.footer]
enabled = true
copyright = true
stack = true

[extra.social]
email = "user_email"
mastodon = "server/@user_name"
twitter = "user_name"
facebook = "user_name"
codeberg = "username"
github = "user_name"
gitlab = "user_name"
bitbucket = "user_name"
hackthebox = "12345"
stackoverflow = "12345/user_name"
linkedin = "user_name"
instagram = "user_name"
lastfm = "user_name"
twitch = "user_name"
reddit = "user_name"
#flickr = "user_name"
keybase = "user_name"
xmpp = "user_name@user_domain"
hackernews = "user_name"

[extra.comments]
system = "none"

[extra.comments.cactus]
site = "site_name"
page_size = 10
guest_posting = true
update_interval = 0

[extra.comments.giscus]
repo = "user_name/repo"
repo_id = ""
category = "Comments"
category_id = ""
mapping = "pathname"
strict = "1"
reactions = "1"
lang = "en"